CREATE TABLE Tags(
TagId INT Identity(1,1) Not Null  Primary key,
Name NVARCHAR(50) NOT NULL,
CreateAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
DeletedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE PostTags(
PostId UNIQUEIDENTIFIER NOT NULL REFERENCES Posts(Id),
TagId INT NOT NULL REFERENCES Tags(TagId),
CONSTRAINT PK_PostTags_PostId_TagId PRIMARY KEY (PostId, TagId)
);
GO